version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=$SERVICE_FQDN_APP
      - HOSTNAME=$SERVICE_FQDN_APP
      - SERVICE_FQDN_APP_3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
